name: CD_stage

'on':
  workflow_call:
    inputs:
      STAGING_ACCOUNT_ID:
        required: true
        type: string
      PRODUCTION_ACCOUNT_ID:
        required: true
        type: string
      ENABLE_PROD:
        required: false
        type: string
      GHACTION_ROLE_NAME:
        required: false
        type: string
        default: github-oidc-role
      DIRECTORY_PATH:
        required: true
        type: string
      CI_RUN_ID:
        required: true
        type: string
    secrets:
      AWS_ROLE_ARN:
        required: true
      AWS_REGION:
        required: true
      SSH_PRIVATE_KEY:
        required: true
      GH_PAT:
        required: true

jobs:
  terragrunt:
    name: Apply Terraform with Terragrunt
    runs-on: ubuntu-latest
    container:
      image: 'ghcr.io/irfan-ssh/terragrunt-docker-image:latest'
    env:
      TERRAGRUNT_TFPATH: /usr/local/bin/terraform
      tf_working_dir: '${{ inputs.DIRECTORY_PATH }}'
    permissions:
      id-token: write
      contents: read
      actions: read
    steps:
      # (Previous steps remain unchanged)

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: terragrunt-plan
          path: ${{ env.tf_working_dir }}
          github-token: ${{ secrets.GH_PAT }}
          repository: ${{ github.repository }}
          run-id: ${{ inputs.CI_RUN_ID }}

      - name: Untar plan files
        run: |
          tar -xvf terragrunt_plan.tar
          rm terragrunt_plan.tar
        working-directory: ${{ env.tf_working_dir }}

      - name: List downloaded files
        run: ls -la ${{ env.tf_working_dir }}

      - name: Check for plan files
        run: |
          if [ -f plan.output ] || [ -f plan_output ]; then
            echo "Plan file found"
          else
            echo "Plan file not found. Directory contents:"
            ls -la
            exit 1
          fi
        working-directory: ${{ env.tf_working_dir }}

      # Terragrunt Apply
      - name: TERRAGRUNT APPLY
        run: |
          if [ -f plan.output ]; then
            terragrunt run-all apply -no-color --terragrunt-non-interactive plan.output | tee apply.output
          elif [ -f plan_output ]; then
            terragrunt run-all apply -no-color --terragrunt-non-interactive plan_output | tee apply.output
          else
            echo "Neither plan.output nor plan_output file found. Contents of directory:"
            ls -la
            exit 1
          fi
        working-directory: '${{ env.tf_working_dir }}'
        
      # (Remaining steps unchanged)