name: CD_stage

'on':
  workflow_call:
    inputs:
      STAGING_ACCOUNT_ID:
        required: true
        type: string
      PRODUCTION_ACCOUNT_ID:
        required: true
        type: string
      ENABLE_PROD:
        required: false
        type: string
      GHACTION_ROLE_NAME:
        required: false
        type: string
        default: github-oidc-role
      DIRECTORY_PATH:
        required: true
        type: string
      CI_RUN_ID:
        required: true
        type: string
    secrets:
      AWS_ROLE_ARN:
        required: true
      AWS_REGION:
        required: true
      SSH_PRIVATE_KEY:
        required: true
      GH_PAT:
        required: true

jobs:
  terragrunt:
    name: Apply Terraform with Terragrunt
    runs-on: ubuntu-latest
    container:
      image: 'ghcr.io/irfan-ssh/terragrunt-docker-image:latest'
    env:
      TERRAGRUNT_TFPATH: /usr/local/bin/terraform
      tf_working_dir: '${{ inputs.DIRECTORY_PATH }}'
      GH_PAT: ${{ github.token }}
    permissions:
      id-token: write
      contents: read
    
    steps:
      # Repository checkout
      - name: Checkout code
        uses: actions/checkout@v3

      # Terraform Setup
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      # Set Terragrunt and Terraform Versions
      - name: Set Terragrunt and Terraform Versions from .terragrunt-version and .terraform-version
        run: |
          TERRAGRUNT_VERSION=$(cat .terragrunt-version)
          echo "Using Terragrunt version: $TERRAGRUNT_VERSION"
          tgenv install $TERRAGRUNT_VERSION
          tgenv use $TERRAGRUNT_VERSION
          terragrunt --version

          TERRAFORM_VERSION=$(cat .terraform-version)
          echo "Using Terraform version: $TERRAFORM_VERSION"
          tfenv install $TERRAFORM_VERSION
          tfenv use $TERRAFORM_VERSION
          terraform --version
        working-directory: ./

      # Configure AWS credentials using OIDC
      - name: Configure AWS credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: >-
            arn:aws:iam::${{ inputs.STAGING_ACCOUNT_ID }}:role/${{ inputs.GHACTION_ROLE_NAME }}
          role-session-name: GitHubActions
          aws-region: '${{ secrets.AWS_REGION }}'

      # Terragrunt Init
      - name: TERRAGRUNT PLAN
        run: |
          echo "Current working directory path: ${{ env.tf_working_dir }}"
          terragrunt run-all plan -no-color -out=plan.output -terragrunt-provider-cache --terragrunt-non-interactive
          terragrunt run-all show -no-color plan.output >> plan_output
          echo "Terragrunt run-all init completed."
        working-directory: '${{ env.tf_working_dir }}'

      # Terragrunt Apply
      - name: TERRAGRUNT APPLY
        run: |
            terragrunt run-all apply -no-color --terragrunt-non-interactive plan.output | tee apply.output
        working-directory: '${{ env.tf_working_dir }}'
        
      # (Remaining steps unchanged)